name: schedule

on:
  schedule:
    - cron: '0 */4 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install and Build
      env:
        TZ: Asia/Shanghai
      run: |
        npm i
        npm run build
        echo `date "+%Y-%m-%d %H:%M:%S"` >> ./public/last-update.txt
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        TZ: Asia/Shanghai
        LANG: zh_CN.UTF-8
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
